# Generated by Django 3.1.1 on 2020-09-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revise', '0008_xyz'),
    ]

    operations = [
        migrations.AddField(
            model_name='xyz',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
