from django.urls import path
from .views import (  PersonDeleteView,
                     PersonUpdateView,
                     PersonViewById,
                     PersonAddView,
                     PersonView,
                     home_view,
                     HomeView,
                     update_person_view,
                     add_person_view,
                     person_view_by_id,
                     person_view,
                     details_view,
                     file_upload_view,
                     session_set_exp,
                     session_get_exp,
                     get_data_by_id,
                     getcookie,
                    )

urlpatterns = [
    path("PersonDeleteView/<int:pk>",PersonDeleteView.as_view(),name='PersonDeleteView'),
    path("PersonUpdateView/<int:pk>",PersonUpdateView.as_view(),name='PersonUpdateView'),
    path("PersonViewById/<int:pk>",PersonViewById.as_view(),name='PersonViewById'),
    path("PersonAddView",PersonAddView.as_view(),name='PersonAddView'),
    path("PersonView",PersonView.as_view(),name='PersonView'),
    path("HomeView",HomeView.as_view(),name='HomeView'),
    path("home",home_view,name='home_view'),
    path("details_view",details_view,name='details_view'),
    path("file_upload_view",file_upload_view,name='file_upload_view'),
    path("session_set_exp",session_set_exp,name='session_set_exp'),
    path("session_get_exp",session_get_exp,name='session_get_exp'),
    path("get_data_by_id/<int:id>",get_data_by_id,name='get_data_by_id'),
    path("getcookie", getcookie, name='getcookie'),
    path("person_view", person_view, name='person_view'),
    path("person_view_by_id/<int:id>", person_view_by_id, name='person_view_by_id'),
    path("add_person_view", add_person_view, name='add_person_view'),
    path("update_person_view/<int:id>", update_person_view, name='update_person_view'),
]
